/* Copyright 2021 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "config_common.h"

/* USB Device descriptor parameter */
#define VENDOR_ID       0x0122
#define PRODUCT_ID      0x1999
#define DEVICE_VER      0x0001
#define MANUFACTURER    IBM
#define PRODUCT         M122

/* key matrix size */
#define MATRIX_ROWS 8
#define MATRIX_COLS 20

#define VIAL_KEYBOARD_UID {0x50, 0xEA, 0x8D, 0xAC, 0x54, 0x91, 0x31, 0x73}
/*
 * Keyboard Matrix Assignments
 *
 * Change this to how you wired your keyboard
 * COLS: AVR pins used for columns, left to right
 * ROWS: AVR pins used for rows, top to bottom
 * DIODE_DIRECTION: COL2ROW = COL = Anode (+), ROW = Cathode (-, marked on diode)
 *                  ROW2COL = ROW = Anode (+), COL = Cathode (-, marked on diode)
 *
 */
#define MATRIX_ROW_PINS { B15, B14, B13, B12, A1, A0, A3, A2 }
#define MATRIX_COL_PINS { B11, B10, B1, B0, A7, A5, A6, C13, C14, C15, B9, A4, A8, A9, A10, A11, A12, A15, B3, B4 }

#define DIODE_DIRECTION COL2ROW


// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
