/* Copyright 2021 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

#define LAYOUT( \
                    K79, K69, K6A, K59, K49, K4A, K39, K29, K2A, K19, K09, K0A,                                                    \
                    K7A, K7B, K6B, K5A, K5B, K4B, K3A, K3B, K2B, K1A, K1B, K0B,                                                    \
    K41, K42,  K44, K54, K55, K56, K57, K47, K48, K58, K5C, K5D, K5E, K4E, K4C, K4F,        K4G, K4H, K5G,    K5F, K5H, K5I, K50,  \
    K51, K31,  K32,   K34, K35, K36, K37, K27, K28, K38, K3C, K3D, K3E, K2E, K2C,   K1F,    K6G, K2G, K3G,    K3F, K3H, K3I, K30,  \
    K21, K22,  K12,     K64, K65, K66, K67, K77, K78, K68, K6C, K6D, K6E, K7E, K1E,              K7G,         K6F, K6H, K6I, K60,  \
    K61, K62,  K03,  K04, K14, K15, K16, K17, K07, K08, K18, K1C, K1D, K0E, K13,            K10, K7J, K6J,    K11, K1H, K1I, K0J,  \
    K72, K71,  K70,        K00,                  K01,                 K73,        K02,           K7F,         K0H,      K0I        \
) { \
    { K00,   K01,   K02,   K03,   K04,   KC_NO, KC_NO, K07,   K08,   K09,   K0A,   K0B,   KC_NO, KC_NO, K0E,   KC_NO, KC_NO, K0H,   K0I,   K0J   }, \
    { K10,   K11,   K12,   K13,   K14,   K15,   K16,   K17,   K18,   K19,   K1A,   K1B,   K1C,   K1D,   K1E,   K1F,   KC_NO, K1H,   K1I,   KC_NO }, \
    { KC_NO, K21,   K22,   KC_NO, KC_NO, KC_NO, KC_NO, K27,   K28,   K29,   K2A,   K2B,   K2C,   KC_NO, K2E,   KC_NO, K2G,   KC_NO, KC_NO, KC_NO }, \
    { K30,   K31,   K32,   KC_NO, K34,   K35,   K36,   K37,   K38,   K39,   K3A,   K3B,   K3C,   K3D,   K3E,   K3F,   K3G,   K3H,   K3I,   KC_NO }, \
    { KC_NO, K41,   K42,   KC_NO, K44,   KC_NO, KC_NO, K47,   K48,   K49,   K4A,   K4B,   K4C,   KC_NO, K4E,   K4F,   K4G,   K4H,   KC_NO, KC_NO }, \
    { K50,   K51,   KC_NO, KC_NO, K54,   K55,   K56,   K57,   K58,   K59,   K5A,   K5B,   K5C,   K5D,   K5E,   K5F,   K5G,   K5H,   K5I,   KC_NO }, \
    { K60,   K61,   K62,   KC_NO, K64,   K65,   K66,   K67,   K68,   K69,   K6A,   K6B,   K6C,   K6D,   K6E,   K6F,   K6G,   K6H,   K6I,   K6J   }, \
    { K70,   K71,   K72,   K73,   KC_NO, KC_NO, KC_NO, K77,   K78,   K79,   K7A,   K7B,   KC_NO, KC_NO, K7E,   K7F,   K7G,   KC_NO, KC_NO, K7J   }, \
}

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
